<table width="100%" bgcolor="#ffffff" border="1" cellpadding="0" cellspacing="0" class='tabelaPadrao' align="center">
    <thead>
        <tr>
            <th>coluna 1</th>
            <th>coluna 2</th>
            <th>coluna 3</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td align='center'>item 1</td>
                <td align='center'>item 2</td>
                <td align='center'>item 3</td>
            </tr>
            <tr>
                <td align='center'>item 11</td>
                <td align='center'>item 22</td>
                <td align='center'>item 33</td>
            </tr>
            <tr>
                <td align='center'>item 111</td>
                <td align='center'>item 222</td>
                <td align='center'>item 333</td>
            </tr>
    </tbody>
</table>
